###############################################################################
# Root variables. Region-parameterized from day one (ADR D2).
# Phase 1a implemented: vpc / transit_gateway / bootstrap / panorama.
# Later phases add their own variables as modules land (see docs/ROADMAP.md).
###############################################################################

# --- Region / global ---------------------------------------------------------

variable "region_a" {
  description = "Primary AWS region (Region A). Delivered first."
  type        = string
  default     = "eu-central-1"
}

variable "region_b" {
  description = "Secondary AWS region (Region B). Phase R2 — multi-region resilience."
  type        = string
  default     = "eu-west-1"
}

variable "enable_region_b" {
  description = "Feature flag: deploy the Region B stack + Global Accelerator (Phase R2)."
  type        = bool
  default     = false
}

variable "name_prefix" {
  description = "Prefix for resource names. Region + role are appended per module (e.g. \"awsha-a-security\")."
  type        = string
  default     = "awsha"
}

variable "common_tags" {
  description = "Tags applied to all resources (provider default_tags)."
  type        = map(string)
  default = {
    Project   = "aws-vmseries-ha-globalprotect"
    ManagedBy = "terraform"
  }
}

# --- CIDR plan (Region A) ----------------------------------------------------
# Non-overlapping /16 per VPC. Region B (Phase R2) mirrors these on 10.2x.0.0/16.

variable "security_vpc_cidr" {
  description = "Security/Transit VPC CIDR (VM-Series HA pair + TGW)."
  type        = string
  default     = "10.10.0.0/16"
}

variable "mgmt_vpc_cidr" {
  description = "Management VPC CIDR (Panorama + SSM jump host)."
  type        = string
  default     = "10.11.0.0/16"
}

variable "spoke1_vpc_cidr" {
  description = "Spoke1 (App) VPC CIDR."
  type        = string
  default     = "10.12.0.0/16"
}

variable "spoke2_vpc_cidr" {
  description = "Spoke2 (DC) VPC CIDR."
  type        = string
  default     = "10.13.0.0/16"
}

# --- Panorama ----------------------------------------------------------------

variable "panorama_private_ip" {
  description = "Static private IP for Panorama in the mgmt VPC panorama subnet (AZ a)."
  type        = string
  default     = "10.11.0.10"
}

variable "panorama_instance_type" {
  description = "Panorama EC2 instance type (PANW sizing)."
  type        = string
  default     = "m5.4xlarge"
}

variable "panorama_ami_id" {
  description = "Explicit Panorama AMI ID. null = look up the Marketplace BYOL AMI (requires a one-time account subscription)."
  type        = string
  default     = null
}

variable "panorama_log_disk_size_gb" {
  description = "Panorama log-collection EBS volume size (GB)."
  type        = number
  default     = 2000
}

variable "panorama_template_stack" {
  description = "Panorama Template Stack name (FW init-cfg tplname=). Must match Phase 2a."
  type        = string
  default     = "AWS-Transit-Stack"
}

variable "panorama_device_group" {
  description = "Panorama Device Group name (FW init-cfg dgname=). Must match Phase 2a."
  type        = string
  default     = "AWS-Transit-DG"
}

variable "panorama_vm_auth_key" {
  description = "VM auth key generated by Phase 2a (auto-loaded from panorama_vm_auth_key.auto.tfvars). Leave empty here."
  type        = string
  default     = ""
  sensitive   = true
}

# --- VM-Series license / device-cert (init-cfg) ------------------------------

variable "fw_auth_code" {
  description = "VM-Series BYOL license auth code."
  type        = string
  default     = ""
  sensitive   = true
}

variable "fw_registration_pin_id" {
  description = "CSP auto-registration PIN ID (device-cert fetch on first boot)."
  type        = string
  default     = ""
  sensitive   = true
}

variable "fw_registration_pin_value" {
  description = "Companion PIN value for fw_registration_pin_id."
  type        = string
  default     = ""
  sensitive   = true
}

# --- Misc --------------------------------------------------------------------

variable "dns_secondary" {
  description = "Secondary DNS for the FW mgmt plane (public resolver). Primary is the VPC resolver (.2)."
  type        = string
  default     = "1.1.1.1"
}

variable "key_name" {
  description = "EC2 key pair NAME (e.g. \"awsha-key\") for Panorama + SSM jump host — NOT a file path. The local .pem path goes in ssh_private_key_file. null = none."
  type        = string
  default     = null
  validation {
    condition     = var.key_name == null || (!strcontains(coalesce(var.key_name, "x"), "/") && !endswith(coalesce(var.key_name, "x"), ".pem"))
    error_message = "key_name must be the EC2 key pair NAME (e.g. \"awsha-key\"), not a file path. Put the .pem path in ssh_private_key_file instead."
  }
}

variable "panorama_admin_username" {
  description = "Panorama admin username (also used by the panos provider in Phase 2a)."
  type        = string
  default     = "admin"
}

variable "panorama_admin_password" {
  description = "Panorama admin password. Set automatically at first boot over SSH (PAN-OS on AWS has no platform password injection). MUST equal phase2-panorama-config panorama_password. Empty = skip auto-set."
  type        = string
  default     = ""
  sensitive   = true
}

variable "ssh_private_key_file" {
  description = "Local path to the private key for key_name, used only by the first-boot Panorama password provisioner. null = ~/.ssh/<key_name>.pem."
  type        = string
  default     = null
}

variable "ssh_public_key" {
  description = "OpenSSH public key (contents of ~/.ssh/<key_name>.pub). When set (and key_name != null), each region creates its own EC2 key pair named key_name from this key — EC2 key pairs are REGION-LOCAL, so a multi-region deploy otherwise fails in Region B with \"key pair does not exist\" until you import it by hand. Empty = assume key_name already exists in every target region (import it yourself)."
  type        = string
  default     = ""
}

# --- Custom domain (OPTIONAL — Route53 delegated subdomain + Let's Encrypt) --
# Off by default: GlobalProtect works fine on the raw EIPs / Global Accelerator
# anycast IPs with a self-signed cert. Turn this on for a branded, browser-
# trusted portal. Nothing is hardcoded to a real domain — you supply every name.
# Requires a ONE-TIME NS delegation of the subdomain (see module output
# custom_domain_name_servers + docs/CONFIGURATION.md).
variable "enable_custom_domain" {
  description = "Create the Route53 subdomain zone + GP portal/gateway DNS records."
  type        = bool
  default     = false
}

variable "custom_domain_subdomain_zone" {
  description = "Delegated subdomain to host in Route53, e.g. \"lab.example.com\". You delegate it once from the parent domain to this zone's name servers."
  type        = string
  default     = ""
}

variable "custom_domain_portal_hostname" {
  description = "Left label for the portal record, e.g. \"gp\" -> gp.<subdomain_zone>. The name GP users type."
  type        = string
  default     = "gp"
}

variable "custom_domain_gateway_labels" {
  description = "Per-region gateway record labels, region key => label, e.g. { region_a = \"gw-a\", region_b = \"gw-b\" }. Each resolves to that region's firewall EIP; use the resulting FQDNs in gp_external_gateways."
  type        = map(string)
  default     = { region_a = "gw-a", region_b = "gw-b" }
}

variable "custom_domain_cert_mode" {
  description = "\"self_signed\" (default) or \"letsencrypt\" (wildcard *.subdomain_zone via DNS-01 against the Route53 zone). letsencrypt needs the NS delegation live first."
  type        = string
  default     = "self_signed"
  validation {
    condition     = contains(["self_signed", "letsencrypt"], var.custom_domain_cert_mode)
    error_message = "custom_domain_cert_mode must be \"self_signed\" or \"letsencrypt\"."
  }
}

variable "custom_domain_letsencrypt_email" {
  description = "Email for the Let's Encrypt account (required when custom_domain_cert_mode = letsencrypt)."
  type        = string
  default     = ""
}

variable "custom_domain_letsencrypt_staging" {
  description = "Use the Let's Encrypt STAGING endpoint (untrusted, high rate limits) — set false for a real browser-trusted cert. Referenced by the acme provider."
  type        = bool
  default     = true
}

# --- PAN-OS versions (pinned + coordinated) ---------------------------------
# Panorama can manage firewalls on the SAME or an OLDER PAN-OS version, never a
# newer one. So panorama_version MUST be >= vmseries_version (enforced below).
# Pin explicit versions (NOT "latest"/"*") for reproducible, matched deploys;
# a trailing "*" is added in the AMI filter to catch hotfix builds.
variable "vmseries_version" {
  description = "VM-Series (firewall) PAN-OS version to pin, e.g. \"11.1.15\". Must exist as a Marketplace AMI for the VM-Series product."
  type        = string
  default     = "11.1.15"
}

variable "panorama_version" {
  description = "Panorama PAN-OS version to pin, e.g. \"11.1.15\" (or a NEWER train like \"12.1.7\"). MUST be >= vmseries_version — Panorama manages same-or-older firewalls only."
  type        = string
  default     = "11.1.15"
}

variable "fw_instance_type" {
  description = "EC2 instance type for the VM-Series firewalls. m5.xlarge (4 vCPU/16 GiB) is the lab default — enough for the 4 required ENIs and cheaper on flex credits; use m5.2xlarge (8 vCPU) for GP/throughput headroom. Keep the Deployment Profile vCPU/FW in sync (4 <-> m5.xlarge, 8 <-> m5.2xlarge)."
  type        = string
  default     = "m5.xlarge"
}

# --- Spoke2 Windows DC (Phase 3) --------------------------------------------

variable "dc_domain_name" {
  description = "AD DS domain FQDN for the spoke2 DC."
  type        = string
  default     = "panw.labs"
}

variable "dc_safe_mode_password" {
  description = "DSRM password used when promoting the DC forest."
  type        = string
  default     = ""
  sensitive   = true
}

variable "dc_promote_to_dc" {
  description = "Promote the spoke2 Windows host to an AD DS forest via user-data."
  type        = bool
  default     = true
}

variable "dc_ad_test_user_name" {
  description = "AD user auto-created after the forest is up (SSM RunCommand), for GP LDAP auth testing."
  type        = string
  default     = "admin"
}

variable "dc_ad_test_user_password" {
  description = "Password for dc_ad_test_user_name. Empty = skip creation entirely."
  type        = string
  default     = ""
  sensitive   = true
}

# --- Global Accelerator (Phase R2) ------------------------------------------

variable "enable_global_accelerator" {
  description = "Create the Global Accelerator fronting the per-region portal EIPs (Phase R2)."
  type        = bool
  default     = false
}

variable "enable_http_redirect" {
  description = "Create a per-region HTTP->HTTPS 301 redirect ALB behind the Global Accelerator :80 listener, so a browser typing http://<portal FQDN> is redirected to https (the GP portal is HTTPS-only and GA is L4, so neither redirects alone). Only takes effect when enable_global_accelerator is also true. See modules/http_redirect_alb."
  type        = bool
  default     = false
}

# --- Region B CIDR plan (mirrors Region A on 10.2x.0.0/16) -------------------

variable "security_vpc_cidr_b" {
  description = "Region B security/transit VPC CIDR."
  type        = string
  default     = "10.20.0.0/16"
}

variable "mgmt_vpc_cidr_b" {
  description = "Region B management VPC CIDR."
  type        = string
  default     = "10.21.0.0/16"
}

variable "spoke1_vpc_cidr_b" {
  description = "Region B spoke1 (app) VPC CIDR."
  type        = string
  default     = "10.22.0.0/16"
}

variable "spoke2_vpc_cidr_b" {
  description = "Region B spoke2 (DC) VPC CIDR."
  type        = string
  default     = "10.23.0.0/16"
}

variable "region_b_create_app" {
  description = "Deploy the app path (NLB/CloudFront/Apache) in Region B too."
  type        = bool
  default     = false
}

variable "region_b_create_dc" {
  description = "Deploy the Windows DC in Region B too."
  type        = bool
  default     = false
}
